spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/gt
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  messages:
    basename: message

